# RELION optimiser; version 4.0.0-commit-1569f0
# --o Class2D/job008/run --iter 25 --i Extract/job005/particles.star --dont_combine_weights_via_disc --preread_images --pool 50 --pad 2 --ctf --tau2_fudge 2 --particle_diameter 200 --K 50 --flatten_solvent --zero_mask --center_classes --oversampling 1 --psi_step 12 --offset_range 5 --offset_step 2 --norm --scale --j 4 --gpu  --pipeline_control Class2D/job008/ 

# version 30001

data_optimiser_general

_rlnOutputRootName                                    Class2D/job008/run
_rlnModelStarFile                                     Class2D/job008/run_it025_model.star
_rlnExperimentalDataStarFile                          Class2D/job008/run_it025_data.star
_rlnOrientSamplingStarFile                            Class2D/job008/run_it025_sampling.star
_rlnCurrentIteration                                            25
_rlnNumberOfIterations                                          25
_rlnDoSplitRandomHalves                                          0
_rlnJoinHalvesUntilThisResolution                         -1.00000
_rlnAdaptiveOversampleOrder                                      1
_rlnAdaptiveOversampleFraction                            0.999000
_rlnRandomSeed                                          1667490555
_rlnParticleDiameter                                    200.000000
_rlnWidthMaskEdge                                                5
_rlnDoZeroMask                                                   1
_rlnDoSolventFlattening                                          1
_rlnDoSolventFscCorrection                                       0
_rlnSolventMaskName                                   None
_rlnSolventMask2Name                                  None
_rlnBodyStarFile                                      None
_rlnTauSpectrumName                                   None
_rlnMaximumCoarseImageSize                                      -1
_rlnHighresLimitExpectation                               -1.00000
_rlnLowresLimitExpectation                                -1.00000
_rlnIncrementImageSize                                          10
_rlnDoMapEstimation                                              1
_rlnDoFastSubsetOptimisation                                     0
_rlnDoExternalReconstruct                                        0
_rlnDoGradientRefine                                             0
_rlnDoStochasticGradientDescent                                  0
_rlnGradEmIters                                                  0
_rlnGradHasConverged                                             0
_rlnGradCurrentStepsize                                   0.000000
_rlnGradSubsetOrder                                              0
_rlnGradSuspendFinerSamplingIter                                -1
_rlnGradSuspendLocalSamplingIter                                -1
_rlnSgdInitialIterationsFraction                          0.300000
_rlnSgdFinalIterationsFraction                            0.200000
_rlnSgdMinimumResolution                                 20.000000
_rlnSgdInitialResolution                                  -1.00000
_rlnSgdFinalResolution                                    -1.00000
_rlnSgdInitialSubsetSize                                        -1
_rlnSgdFinalSubsetSize                                          -1
_rlnSgdMuFactor                                           0.000000
_rlnSgdSkipAnneal                                                0
_rlnSgdClassInactivityThreshold                           0.000000
_rlnSgdSubsetSize                                               -1
_rlnSgdWriteEverySubset                                         10
_rlnSgdStepsize                                           -1.00000
_rlnSgdStepsizeScheme                                 ""
_rlnTau2FudgeScheme                                   ""
_rlnTau2FudgeArg                                          2.000000
_rlnMaximumSignificantPoses                                     -1
_rlnDoAutoRefine                                                 0
_rlnDoAutoSampling                                               0
_rlnAutoLocalSearchesHealpixOrder                                4
_rlnNumberOfIterWithoutResolutionGain                            1
_rlnBestResolutionThusFar                                 0.097105
_rlnNumberOfIterWithoutChangingAssignments                       3
_rlnDoSkipAlign                                                  0
_rlnDoSkipRotate                                                 0
_rlnOverallAccuracyRotations                              1.200000
_rlnOverallAccuracyTranslationsAngst                      0.814200
_rlnChangesOptimalOrientations                            8.903480
_rlnChangesOptimalOffsets                                 1.933734
_rlnChangesOptimalClasses                                 0.025073
_rlnSmallestChangesOrientations                           4.339306
_rlnSmallestChangesOffsets                                1.628140
_rlnSmallestChangesClasses                                       0
_rlnLocalSymmetryFile                                 None
_rlnDoHelicalRefine                                              0
_rlnIgnoreHelicalSymmetry                                        0
_rlnFourierMask                                       None
_rlnHelicalTwistInitial                                   0.000000
_rlnHelicalRiseInitial                                    0.000000
_rlnHelicalCentralProportion                              0.300000
_rlnNrHelicalNStart                                              1
_rlnHelicalMaskTubeInnerDiameter                          -1.00000
_rlnHelicalMaskTubeOuterDiameter                          -1.00000
_rlnHelicalSymmetryLocalRefinement                               0
_rlnHelicalSigmaDistance                                  -1.00000
_rlnHelicalKeepTiltPriorFixed                                    0
_rlnHasConverged                                                 0
_rlnHasHighFscAtResolLimit                                       0
_rlnHasLargeSizeIncreaseIterationsAgo                            0
_rlnDoCorrectNorm                                                1
_rlnDoCorrectScale                                               1
_rlnDoCorrectCtf                                                 1
_rlnDoCenterClasses                                              1
_rlnDoIgnoreCtfUntilFirstPeak                                    0
_rlnCtfDataArePhaseFlipped                                       0
_rlnDoOnlyFlipCtfPhases                                          0
_rlnRefsAreCtfCorrected                                          1
_rlnFixSigmaNoiseEstimates                                       0
_rlnFixSigmaOffsetEstimates                                      0
_rlnMaxNumberOfPooledParticles                                 200
 
